export const bookingData = [
    {
        id: 1,
        customerName: "Rohan",
        cratedAt:"21/03/2022",
        totalAmount: "100",
        status: "success",
        lastLogin: "01/03/1999",
        discount: "2999",
        payment: "23452",
        shipping: "asd",
        voucher: "asdf",
        tax: "30%",
        shippingLocation: "Dehradun",
        total: "39999" ,
        category: "Electronics",
        price: "34567", 
        email: "test1@gmail.com" , 
        contactNo: "2345678",
        country: "India",
        state: "uttrakhund",
        city: "Dehradun",
        ZipCode: "246063",
        address: "ISBT",
        landmark: "Rispana pull"
        
    },
    {
        id: 2,
        customerName: "sohan",
        cratedAt:"21/03/2022",
        totalAmount: "100",
        status: "success",
        lastLogin: "01/03/1999",
        discount: "2999",
        payment: "23452",
        shipping: "asd",
        voucher: "asdf",
        tax: "30%",
        shippingLocation: "Dehradun",
        total: "39999"    ,
        category: "Electronics",
        price: "34567",
        email: "test1@gmail.com" , 
        contactNo: "2345678"  ,
        country: "India",
        state: "uttrakhund",
        city: "Dehradun",
        ZipCode: "246063",
        address: "ISBT",
        landmark: "Rispana pull" 
    },
    {
        id: 3,
        customerName: "Ranm",
        cratedAt:"25/03/2022",
        totalAmount: "1000",
        status: "success",
        lastLogin: "01/03/1999",
        discount: "2999",
        payment: "23452",
        shipping: "asd",
        voucher: "asdf",
        tax: "30%",
        shippingLocation: "Dehradun",
        total: "39999" ,   
        category: "Electronics",
        price: "34567",  
        email: "test1@gmail.com" , 
        contactNo: "2345678" ,
        country: "India",
        state: "uttrakhund",
        city: "Dehradun",
        ZipCode: "246063",
        address: "ISBT",
        landmark: "Rispana pull"
    },
    {
        id: 4,
        customerName: "Rohan",
        cratedAt:"11/03/2022",
        totalAmount: "100",
        status: "failed",
        lastLogin: "01/03/1999",
        discount: "2999",
        payment: "23452",
        shipping: "asd",
        voucher: "asdf",
        tax: "30%",
        shippingLocation: "Dehradun",
        total: "39999"  ,  
        category: "Electronics",
        price: "34567",
        email: "test1@gmail.com" , 
        contactNo: "2345678" ,
        country: "India",
        state: "uttrakhund",
        city: "Dehradun",
        ZipCode: "246063",
        address: "ISBT",
        landmark: "Rispana pull"  
    },
    {
        id: 5,
        customerName: "Rohan",
        cratedAt:"21/03/2022",
        totalAmount: "100",
        status: "success",
        lastLogin: "01/03/1999",
        discount: "2999",
        payment: "23452",
        shipping: "asd",
        voucher: "asdf",
        tax: "30%",
        shippingLocation: "Dehradun",
        total: "39999" ,
        category: "Electronics",
        price: "34567",
        email: "test1@gmail.com" , 
        contactNo: "2345678",
        country: "India",
        state: "uttrakhund",
        city: "Dehradun",
        ZipCode: "246063",
        address: "ISBT",
        landmark: "Rispana pull"      
        
    },
    {
        id: 6,
        customerName: "laxman",
        cratedAt:"21/09/2022",
        totalAmount: "788",
        status: "success",
        lastLogin: "01/03/1999",
        discount: "2999",
        payment: "23452",
        shipping: "asd",
        voucher: "asdf",
        tax: "30%",
        shippingLocation: "Dehradun",
        total: "39999" ,
        category: "Electronics",
        price: "34567",
        email: "test1@gmail.com" , 
        contactNo: "2345678" ,
        country: "India",
        state: "uttrakhund",
        city: "Dehradun",
        ZipCode: "246063",
        address: "ISBT",
        landmark: "Rispana pull"     
        
    },

]

export const bookingProduct=[
    {
        id : 1,
        product: "shoes",
        quantitys: "2",
        prices: "8999",
        subTotal: "67777",
        category: "Denim"
    },
    {
        id : 2,
        product: "shoes",
        quantitys: "4",
        prices: "8999",
        subTotal: "67777",
        category: "Denim"
    },
    {
        id : 3,
        product: "shoes",
        quantitys: "5",
        prices: "8999",
        subTotal: "67777",
        category: "Denim"
    },
    {
        id : 4,
        product: "shoes",
        quantitys: "6",
        prices: "8999",
        subTotal: "67777",
        category: "Denim"
    },
    {
        id : 5,
        product: "shoes",
        quantitys: "1",
        prices: "8999",
        subTotal: "67777",
        category: "Denim"
    }
]